"""hashes table

Revision ID: 2922e94e7067
Revises: e5e3dbd7322c
Create Date: 2021-04-13 00:10:44.254331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2922e94e7067'
down_revision = 'e5e3dbd7322c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashes',
    sa.Column('hash_id', sa.Integer(), nullable=False),
    sa.Column('account_hash', sa.BINARY(length=128), nullable=True),
    sa.Column('account_last_updated', sa.DateTime(), nullable=True),
    sa.Column('inventory_hash', sa.BINARY(length=128), nullable=True),
    sa.Column('inventory_last_updated', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('fk_hashes_account_id_accounts')),
    sa.PrimaryKeyConstraint('hash_id', name=op.f('pk_hashes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashes')
    # ### end Alembic commands ###
