"""descriptions table tags columns

Revision ID: 6c9911c6de88
Revises: 8ae26eb23b3c
Create Date: 2021-04-10 01:06:56.697106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9911c6de88'
down_revision = '8ae26eb23b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_border_tag', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('game_tag', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('item_type_tag', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rarity_tag', sa.String(), nullable=True))
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('rarity_tag')
        batch_op.drop_column('item_type_tag')
        batch_op.drop_column('game_tag')
        batch_op.drop_column('card_border_tag')

    # ### end Alembic commands ###
