"""items table item_id column

Revision ID: 8ae26eb23b3c
Revises: 9054937779b0
Create Date: 2021-04-09 22:25:57.929181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae26eb23b3c'
down_revision = '9054937779b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('pk_items')
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=False))
        batch_op.alter_column('asset_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_items_asset_id'), ['asset_id'], unique=False)
        batch_op.create_primary_key('pk_items', ['item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('pk_items')
        batch_op.drop_index(batch_op.f('ix_items_asset_id'))
        batch_op.alter_column('asset_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('item_id')
        batch_op.create_primary_key('pk_items', ['asset_id'])

    # ### end Alembic commands ###
