"""items and descriptions tables

Revision ID: 9054937779b0
Revises: efb08bd87a58
Create Date: 2021-04-08 23:52:06.837171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9054937779b0'
down_revision = 'efb08bd87a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descriptions',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.SmallInteger(), nullable=True),
    sa.Column('icon_url_large', sa.String(), nullable=True),
    sa.Column('market_hash_name', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('class_id', name=op.f('pk_descriptions'))
    )
    op.create_table('items',
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('fk_items_account_id_accounts')),
    sa.ForeignKeyConstraint(['class_id'], ['descriptions.class_id'], name=op.f('fk_items_class_id_descriptions')),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_items'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_accounts_login_key'), ['login_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_accounts_login_key'), type_='unique')

    op.drop_table('items')
    op.drop_table('descriptions')
    # ### end Alembic commands ###
