"""descriptions table market name column

Revision ID: e5e3dbd7322c
Revises: 6c9911c6de88
Create Date: 2021-04-12 16:31:33.560213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e3dbd7322c'
down_revision = '6c9911c6de88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('descriptions', schema=None) as batch_op:
        batch_op.drop_column('market_name')

    # ### end Alembic commands ###
