"""accounts table sentry and nickname columns added

Revision ID: efb08bd87a58
Revises: da3e68d9380f
Create Date: 2021-04-02 20:40:09.421010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb08bd87a58'
down_revision = 'da3e68d9380f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('sentry', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_accounts_steam_id'), 'accounts', ['steam_id'], unique=False)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=False)
    op.create_unique_constraint(None, 'accounts', ['login_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_steam_id'), table_name='accounts')
    op.drop_column('accounts', 'sentry')
    op.drop_column('accounts', 'nickname')
    # ### end Alembic commands ###
