"""accounts table sentry and nickname columns added

Revision ID: efb08bd87a58
Revises: da3e68d9380f
Create Date: 2021-04-02 20:40:09.421010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb08bd87a58'
down_revision = 'da3e68d9380f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sentry', sa.LargeBinary(), nullable=True))
        batch_op.create_unique_constraint(None, ['login_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sentry')
        batch_op.drop_column('nickname')
    # ### end Alembic commands ###
